# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

index:
    path: /
    defaults: { _controller: 'App\Controller\MainController::index' }

listTask:
    path: /listTask
    defaults: { _controller: 'App\Controller\TaskController::listAction' }

addTask:
    path: /addTask
    defaults: { _controller: 'App\Controller\TaskController::addAction' }

updateTask:
    path: /updateTask/{id}
    defaults: { _controller: 'App\Controller\TaskController::updateAction' }
    requirements: 
        page: '\d+'

removeTask:
    path: /removeTask/{id}
    defaults: { _controller: 'App\Controller\TaskController::removeAction'}
    requirements:
        page: '\d+'

searchAction:
    path: /search
    defaults: { _controller: 'App\Controller\TaskController::searchAction' }

test:
    path: /test
    defaults: { _controller: 'App\Controller\TaskController::test' }